export const config = {
    options: {
        allowStealFocus: false,
        authAPIVersion: 1,
        bookmarkThumbHeight: 150,
        bookmarkThumbWidth: 90,
        dropEnabled: true,
        footerPanelEnabled: true,
        headerPanelEnabled: true,
        leftPanelEnabled: true,
        limitLocales: false,
        metrics: [
            {
                type: "watch",
                minWidth: 0,
                maxWidth: 312,
                minHeight: 0,
                maxHeight: 390,
            },
            {
                type: "mobileportrait",
                minWidth: 312,
                maxWidth: 415,
                minHeight: 640,
                maxHeight: 813,
            },
            {
                type: "mobilelandscape",
                minWidth: 640,
                maxWidth: 813,
                minHeight: 360,
                maxHeight: 415,
            },
            {
                type: "desktop",
                minWidth: 800,
                maxWidth: 100000,
                minHeight: 415,
                maxHeight: 100000,
            },
        ],
        multiSelectionMimeType: "application/zip",
        navigatorEnabled: true,
        openTemplate: "http://universalviewer.io?manifest={0}",
        overrideFullScreen: false,
        pagingEnabled: true,
        pagingOptionEnabled: true,
        pessimisticAccessControl: false,
        preserveViewport: false,
        rightPanelEnabled: true,
        saveUserSettings: false,
        clickToZoomEnabled: true,
        searchWithinEnabled: true,
        termsOfUseEnabled: true,
        theme: "uv-hr-HR-theme",
        tokenStorage: "session",
        useArrowKeysToNavigate: false,
        zoomToSearchResultEnabled: true,
        zoomToBoundsEnabled: true,
    },
    modules: {
        contentLeftPanel: {
            options: {
                autoExpandTreeEnabled: false,
                autoExpandTreeIfFewerThan: 20,
                branchNodesExpandOnClick: true,
                branchNodesSelectable: false,
                defaultToTreeEnabled: false,
                defaultToTreeIfGreaterThan: 0,
                elideCount: 40,
                expandFullEnabled: true,
                galleryThumbChunkedResizingThreshold: 400,
                galleryThumbHeight: 320,
                galleryThumbLoadPadding: 3,
                galleryThumbWidth: 200,
                oneColThumbHeight: 320,
                oneColThumbWidth: 200,
                pageModeEnabled: true,
                panelAnimationDuration: 250,
                panelCollapsedWidth: 30,
                panelExpandedWidth: 255,
                panelOpen: true,
                tabOrder: "",
                thumbsCacheInvalidation: {
                    enabled: true,
                    paramType: "#",
                },
                thumbsEnabled: true,
                thumbsExtraHeight: 8,
                thumbsImageFadeInDuration: 300,
                thumbsLoadRange: 15,
                treeEnabled: true,
                twoColThumbHeight: 150,
                twoColThumbWidth: 90,
            },
            content: {
                collapse: "Sakrij sadržaj",
                collapseFull: "Sakrij galeriju",
                date: "datum",
                expand: "Prikaži sadržaj",
                expandFull: "Prikaži galeriju",
                index: "Sadržaj",
                manifestRanges: "Manifest",
                searchResult: "Broj rezultata pretrage: {0}",
                searchResults: "Broj rezultata pretrage: {0}",
                sortBy: "Sortiraj prema:",
                thumbnails: "Sličice",
                title: "Sadržaj",
                volume: "volumen",
            },
        },
        dialogue: {
            topCloseButtonEnabled: false,
            content: {
                close: "Zatvori",
            },
        },
        downloadDialogue: {
            options: {
                confinedImageSize: 1000,
                currentViewDisabledPercentage: 90,
                maxImageWidth: 5000,
                optionsExplanatoryTextEnabled: false,
                selectionEnabled: false,
            },
            content: {
                currentViewAsJpg: "Trenutni prikaz {0} x {1}px (jpg)",
                currentViewAsJpgExplanation: "Otvori u novom prozoru",
                download: "Preuzmi",
                downloadSelection: "Preuzmi odabrane stranice",
                downloadSelectionExplanation: "Odaberite stranice za preuzimanje.",
                editSettings: "Uredi postavke",
                entireDocument: "Cijeli dokument ({0})",
                entireFileAsOriginal: "Cijela datoteka",
                noneAvailable: "Nema dostupnih mogućnosti za preuzimanje.",
                pagingNote:
                    "Za dodatne mogućnosti isključite prikaz na dvije stranice.",
                preview: "Pregled",
                title: "Preuzmi",
                wholeImageHighRes: "Slika {0} x {1}px ({2})",
                wholeImageHighResExplanation: "Otvori u novom prozoru.",
                wholeImagesHighRes: "Slika ({0})",
                wholeImagesHighResExplanation: "Otvori u dva nova prozora.",
                wholeImageLowResAsJpg: "Slika {0} x {1}px (jpg)",
                wholeImageLowResAsJpgExplanation: "Otvori u novom prozoru.",
                individualPages: "Pojedine stranice",
                allPages: "Sve stranice",
            },
        },
        footerPanel: {
            options: {
                autocompleteAllowWords: false,
                bookmarkEnabled: false,
                downloadEnabled: true,
                embedEnabled: false,
                feedbackEnabled: false,
                fullscreenEnabled: true,
                minimiseButtons: true,
                moreInfoEnabled: false,
                openEnabled: false,
                printEnabled: false,
                shareEnabled: false,
            },
            content: {
                bookmark: "Dodaj u favorite",
                download: "Preuzmi",
                embed: "Ugradi",
                exitFullScreen: "Izlaz iz cijelog zaslona",
                feedback: "Povratne informacije",
                fullScreen: "Cijeli zaslon",
                moreInfo: "Više informacija",
                open: "Otvori",
                share: "Podijeli",
            },
        },
        genericDialogue: {
            content: {
                emptyValue: "unesite vrijednost.",
                invalidNumber: "Unesite valjani broj.",
                noMatches: "Nema pronađenih rezultata.",
                ok: "U redu",
                pageNotFound:
                    "Ovaj objekt ne sadrži stranicu s brojem koji ste unijeli. Pokušajte se prebaciti na opciju numeriranja 'slika'.",
                refresh: "Osvježi",
            },
        },
        headerPanel: {
            options: {
                centerOptionsEnabled: true,
                localeToggleEnabled: false,
                settingsButtonEnabled: false,
            },
        },
        helpDialogue: {
            content: {
                text: "zamjenski tekst",
                title: "Pomoć",
            },
        },
        moreInfoRightPanel: {
            options: {
                canvasDisplayOrder: "",
                canvasExclude: "",
                copyToClipboardEnabled: false,
                manifestDisplayOrder: "",
                manifestExclude: "",
                panelAnimationDuration: 250,
                panelCollapsedWidth: 30,
                panelExpandedWidth: 255,
                panelOpen: false,
                rtlLanguageCodes: "ar, ara, dv, div, he, heb, ur, urd",
                showAllLanguages: false,
                textLimit: 4,
                textLimitType: "lines",
            },
            content: {
                attribution: "Značajke",
                collapse: "Sakrij informacije",
                collapseFull: "Sakrij galeriju",
                description: "Opis",
                expand: "Prikaži informacije",
                expandFull: "Prikaži galeriju",
                holdingText: "Vaš modul ide ovdje!",
                less: "manje",
                license: "Licenca",
                logo: "Logo",
                more: "više",
                noData: "Nema podataka za prikaz",
                page: "Stranica",
                title: "Više informacija",
                manifestHeader: "O predmetu",
                canvasHeader: "O slici",
                copyToClipboard: "Kopiraj u međuspremnik",
                copiedToClipboard: "Kopirano u međuspremnik",
            },
        },
        multiSelectDialogue: {
            options: {
                galleryThumbChunkedResizingEnabled: true,
                galleryThumbChunkedResizingThreshold: 400,
                galleryThumbHeight: 320,
                galleryThumbLoadPadding: 3,
                galleryThumbWidth: 200,
                pageModeEnabled: true,
            },
            content: {
                select: "Preuzmi",
                selectAll: "Označi sve",
                title: "Odaberi stranice za preuzimanje",
            },
        },
        pagingHeaderPanel: {
            options: {
                autoCompleteBoxEnabled: true,
                autocompleteAllowWords: false,
                galleryButtonEnabled: true,
                imageSelectionBoxEnabled: false,
                pageModeEnabled: false,
                pagingToggleEnabled: true,
            },
            content: {
                close: "Zatvori",
                emptyValue: "Unesite vrijednost",
                first: "Prva",
                firstImage: "Prva slika",
                firstPage: "Prva stranica",
                folio: "List",
                gallery: "Galerija",
                go: "Idi",
                help: "Pomoć",
                image: "Slika",
                last: "Zadnja",
                lastImage: "Zadnja slika",
                lastPage: "Zadnja stranica",
                next: "Sljedeća",
                nextImage: "Sljedeća slika",
                nextPage: "Sljedeća stranica",
                of: "od {0}",
                oneUp: "Prikaz jedne stranice",
                page: "Stranica",
                pageSearchLabel: "Pretraži po broju stranice",
                previous: "Prethodna",
                previousImage: "Prethodna slika",
                previousPage: "Prethodna stranica",
                settings: "Postavke",
                twoUp: "Prikaz na dvije stranice",
            },
        },
        openSeadragonCenterPanel: {
            options: {
                animationTime: 0.15,
                autoHideControls: true,
                requiredStatementEnabled: true,
                blendTime: 0,
                constrainDuringPan: false,
                controlsFadeAfterInactive: 1500,
                controlsFadeDelay: 250,
                controlsFadeLength: 250,
                defaultZoomLevel: 0,
                immediateRender: false,
                maxZoomPixelRatio: 1.5,
                navigatorPosition: "BOTTOM_RIGHT",
                pageGap: 50,
                showHomeControl: false,
                trimAttributionCount: 150,
                visibilityRatio: 0.5,
            },
            content: {
                attribution: "Značajke",
                goHome: "Povratak",
                imageUnavailable: "Slika je nedostupna",
                next: "Sljedeća",
                previous: "Prethodna",
                rotateRight: "Rotiraj udesno",
                zoomIn: "uvećaj",
                zoomOut: "umanji",
            },
        },
        searchFooterPanel: {
            options: {
                elideDetailsTermsCount: 20,
                elideResultsTermsCount: 10,
                forceImageMode: false,
                pageModeEnabled: true,
                positionMarkerEnabled: true,
            },
            content: {
                clearSearch: "Obriši",
                defaultLabel: "-",
                displaying: "{0} {1} od {2}",
                enterKeyword: "Unesite ključnu riječ",
                image: "slika",
                imageCaps: "Slika",
                instanceFound: "Pronađene pojeve: 1 od '{0}'",
                instancesFound: "Pronađene pojave: {0} od '{1}' ",
                nextResult: "Sljedeći rezultat",
                page: "stranica",
                pageCaps: "Stranica",
                previousResult: "Prethodni rezultat",
                print: "Ispis",
                resultFoundFor: "pronađeni rezultati za",
                resultsFoundFor: "pronađeni rezultati za",
                searchWithin: "Pretraži u ovom objektu:",
            },
        },
        settingsDialogue: {
            content: {
                locale: "Jezik",
                navigatorEnabled: "Uključi navigaciju",
                clickToZoomEnabled: "Uvećajte klikom miša",
                pagingEnabled: "Prikaz na dvije stranica",
                reduceMotion: "Smanji kretanje (onemogućuje animacije)",
                preserveViewport: "Zadrži uvećanje",
                title: "Postavke",
                website:
                    "<a href='https://github.com/universalviewer/universalviewer#contributors'>više informacija</a>",
            },
        },
        shareDialogue: {
            options: {
                embedTemplate:
                    '<iframe src="{0}" width="{1}" height="{2}" allowfullscreen frameborder="0"></iframe>',
                instructionsEnabled: false,
                shareFrameEnabled: true,
                shareManifestsEnabled: true,
            },
            content: {
                customSize: "prilagodi",
                embed: "Ugradi",
                embedInstructions:
                    "Kako biste ugradili ovaj objekt na svoju web stranicu, kopirajte i zalijepite donji kod. ",
                height: "Visina",
                iiif: "IIIF Manifest",
                share: "Podijeli",
                shareInstructions:
                    "Kako biste podijelili ovaj objekt, kopirajte donji URL. ",
                size: "Veličina:",
                width: "Širina",
            },
        },
        authDialogue: {
            content: {
                cancel: "Odustani",
                confirm: "Potvrdi",
            },
        },
        clickThroughDialogue: {
            content: {
                viewTerms: "Pročitajte uvjete i pravila korištenja",
            },
        },
        loginDialogue: {
            content: {
                login: "Prijava",
                logout: "Odjava",
                cancel: "Odustani",
            },
        },
        mobileFooterPanel: {
            content: {
                rotateRight: "Rotiraj udesno",
                moreInfo: "Više informacija",
                zoomIn: "Uvećaj",
                zoomOut: "Umanji",
            },
        },
        restrictedDialogue: {
            content: {
                cancel: "Odustani",
            },
        },
    },
    localisation: {
        label: "English (GB)",
        locales: [
            {
                name: "cy-GB",
                label: "Cymraeg",
            },
            {
                name: "en-GB",
                label: "English (GB)",
            },
            {
                name: "fr-FR",
                label: "Français (FR)",
            },
            {
                name: "pl-PL",
                label: "Polski",
            },
            {
                name: "sv-SE",
                label: "Svenska",
            },
            {
                name: "xx-XX",
                label: "English (GB) (xx-XX)",
            },
            {
                name: "hr-HR",
                label: "Hrvatski",
            },
        ],
    },
    content: {
        authCORSError:
            "Vaš preglednik ne podržava CORS, nadogradite ga kako biste vidjeli ovaj sadržaj.",
        authorisationFailedMessage:
            "Vaš pokušaj prijave nije bio uspješan. Molimo Vas pokušajte ponovno.",
        canvasIndexOutOfRange: "Indeks platna se nalazi izvan dopuštenog raspona.",
        fallbackDegradedLabel: "Prijava",
        fallbackDegradedMessage:
            "Prijavite se kako biste pogledali ovaj sadržaj u punoj rezoluciji.",
        forbiddenResourceMessage: "Nemate pravo pristupa ovoj slici",
        mediaViewer: "Preglednik Medija",
        skipToDownload: "Preskočite do preuzimanja i drugih formata",
        termsOfUse: "Uvjeti korištenja",
    },
};

